/*
 *  Copyright (C) 2006 - 2008 Stephen F. Booth <me@sbooth.org>
 *  All Rights Reserved
 */

#import "GenreUtilities.h"

// ========================================
// Returns an array containing the ID3v1 genres and WinAmp extensions
// ========================================
NSArray * genres()
{
	return [[NSArray alloc] initWithObjects:
			// ID3v1 genres
			NSLocalizedString(@"Blues", @"Musical genre"),
			NSLocalizedString(@"Classic Rock", @"Musical genre"),
			NSLocalizedString(@"Country", @"Musical genre"),
			NSLocalizedString(@"Dance", @"Musical genre"),
			NSLocalizedString(@"Disco", @"Musical genre"),
			NSLocalizedString(@"Funk", @"Musical genre"),
			NSLocalizedString(@"Grunge", @"Musical genre"),
			NSLocalizedString(@"Hip-Hop", @"Musical genre"),
			NSLocalizedString(@"Jazz", @"Musical genre"),
			NSLocalizedString(@"Metal", @"Musical genre"),
			NSLocalizedString(@"New Age", @"Musical genre"),
			NSLocalizedString(@"Oldies", @"Musical genre"),
			NSLocalizedString(@"Other", @"Musical genre"),
			NSLocalizedString(@"Pop", @"Musical genre"),
			NSLocalizedString(@"R&B", @"Musical genre"),
			NSLocalizedString(@"Rap", @"Musical genre"),
			NSLocalizedString(@"Reggae", @"Musical genre"),
			NSLocalizedString(@"Rock", @"Musical genre"),
			NSLocalizedString(@"Techno", @"Musical genre"),
			NSLocalizedString(@"Industrial", @"Musical genre"),
			NSLocalizedString(@"Alternative", @"Musical genre"),
			NSLocalizedString(@"Ska", @"Musical genre"),
			NSLocalizedString(@"Death metal", @"Musical genre"),
			NSLocalizedString(@"Pranks", @"Musical genre"),
			NSLocalizedString(@"Soundtrack", @"Musical genre"),
			NSLocalizedString(@"Euro-Techno", @"Musical genre"),
			NSLocalizedString(@"Ambient", @"Musical genre"),
			NSLocalizedString(@"Trip-hop", @"Musical genre"),
			NSLocalizedString(@"Vocal", @"Musical genre"),
			NSLocalizedString(@"Jazz+Funk", @"Musical genre"),
			NSLocalizedString(@"Fusion", @"Musical genre"),
			NSLocalizedString(@"Trance", @"Musical genre"),
			NSLocalizedString(@"Classical", @"Musical genre"),
			NSLocalizedString(@"Instrumental", @"Musical genre"),
			NSLocalizedString(@"Acid", @"Musical genre"),
			NSLocalizedString(@"House", @"Musical genre"),
			NSLocalizedString(@"Game", @"Musical genre"),
			NSLocalizedString(@"Sound Clip", @"Musical genre"),
			NSLocalizedString(@"Gospel", @"Musical genre"),
			NSLocalizedString(@"Noise", @"Musical genre"),
			NSLocalizedString(@"Alt. Rock", @"Musical genre"),
			NSLocalizedString(@"Bass", @"Musical genre"),
			NSLocalizedString(@"Soul", @"Musical genre"),
			NSLocalizedString(@"Punk", @"Musical genre"),
			NSLocalizedString(@"Space", @"Musical genre"),
			NSLocalizedString(@"Meditative", @"Musical genre"),
			NSLocalizedString(@"Instrumental pop", @"Musical genre"),
			NSLocalizedString(@"Instrumental rock", @"Musical genre"),
			NSLocalizedString(@"Ethnic", @"Musical genre"),
			NSLocalizedString(@"Gothic", @"Musical genre"),
			NSLocalizedString(@"Darkwave", @"Musical genre"),
			NSLocalizedString(@"Techno-Industrial", @"Musical genre"),
			NSLocalizedString(@"Electronic", @"Musical genre"),
			NSLocalizedString(@"Pop-Folk", @"Musical genre"),
			NSLocalizedString(@"Eurodance", @"Musical genre"),
			NSLocalizedString(@"Dream", @"Musical genre"),
			NSLocalizedString(@"Southern Rock", @"Musical genre"),
			NSLocalizedString(@"Comedy", @"Musical genre"),
			NSLocalizedString(@"Cult", @"Musical genre"),
			NSLocalizedString(@"Gangsta", @"Musical genre"),
			NSLocalizedString(@"Top 40", @"Musical genre"),
			NSLocalizedString(@"Christian Rap", @"Musical genre"),
			NSLocalizedString(@"Pop/Funk", @"Musical genre"),
			NSLocalizedString(@"Jungle", @"Musical genre"),
			NSLocalizedString(@"Native American", @"Musical genre"),
			NSLocalizedString(@"Cabaret", @"Musical genre"),
			NSLocalizedString(@"New Wave", @"Musical genre"),
			NSLocalizedString(@"Psychedelic", @"Musical genre"),
			NSLocalizedString(@"Rave", @"Musical genre"),
			NSLocalizedString(@"Showtunes", @"Musical genre"),
			NSLocalizedString(@"Trailer", @"Musical genre"),
			NSLocalizedString(@"Lo-Fi", @"Musical genre"),
			NSLocalizedString(@"Tribal", @"Musical genre"),
			NSLocalizedString(@"Acid Punk", @"Musical genre"),
			NSLocalizedString(@"Acid Jazz", @"Musical genre"),
			NSLocalizedString(@"Polka", @"Musical genre"),
			NSLocalizedString(@"Retro", @"Musical genre"),
			NSLocalizedString(@"Musical", @"Musical genre"),
			NSLocalizedString(@"Rock & Roll", @"Musical genre"),
			NSLocalizedString(@"Hard Rock", @"Musical genre"),

			// WinAmp extensions
			NSLocalizedString(@"Folk", @"Musical genre"),
			NSLocalizedString(@"Folk-Rock", @"Musical genre"),
			NSLocalizedString(@"National Folk", @"Musical genre"),
			NSLocalizedString(@"Swing", @"Musical genre"),
			NSLocalizedString(@"Fast Fusion", @"Musical genre"),
			NSLocalizedString(@"Bebob", @"Musical genre"),
			NSLocalizedString(@"Latin", @"Musical genre"),
			NSLocalizedString(@"Revival", @"Musical genre"),
			NSLocalizedString(@"Celtic", @"Musical genre"),
			NSLocalizedString(@"Bluegrass", @"Musical genre"),
			NSLocalizedString(@"Avantgarde", @"Musical genre"),
			NSLocalizedString(@"Gothic Rock", @"Musical genre"),
			NSLocalizedString(@"Progressive Rock", @"Musical genre"),
			NSLocalizedString(@"Psychedelic Rock", @"Musical genre"),
			NSLocalizedString(@"Symphonic Rock", @"Musical genre"),
			NSLocalizedString(@"Slow Rock", @"Musical genre"),
			NSLocalizedString(@"Big Band", @"Musical genre"),
			NSLocalizedString(@"Chorus", @"Musical genre"),
			NSLocalizedString(@"Easy Listening", @"Musical genre"),
			NSLocalizedString(@"Acoustic", @"Musical genre"),
			NSLocalizedString(@"Humour", @"Musical genre"),
			NSLocalizedString(@"Speech", @"Musical genre"),
			NSLocalizedString(@"Chanson", @"Musical genre"),
			NSLocalizedString(@"Opera", @"Musical genre"),
			NSLocalizedString(@"Chamber Music", @"Musical genre"),
			NSLocalizedString(@"Sonata", @"Musical genre"),
			NSLocalizedString(@"Symphony", @"Musical genre"),
			NSLocalizedString(@"Booty Bass", @"Musical genre"),
			NSLocalizedString(@"Primus", @"Musical genre"),
			NSLocalizedString(@"Porn Groove", @"Musical genre"),
			NSLocalizedString(@"Satire", @"Musical genre"),
			NSLocalizedString(@"Slow Jam", @"Musical genre"),
			NSLocalizedString(@"Club", @"Musical genre"),
			NSLocalizedString(@"Tango", @"Musical genre"),
			NSLocalizedString(@"Samba", @"Musical genre"),
			NSLocalizedString(@"Folklore", @"Musical genre"),
			NSLocalizedString(@"Ballad", @"Musical genre"),
			NSLocalizedString(@"Power Ballad", @"Musical genre"),
			NSLocalizedString(@"Rhythmic Soul", @"Musical genre"),
			NSLocalizedString(@"Freestyle", @"Musical genre"),
			NSLocalizedString(@"Duet", @"Musical genre"),
			NSLocalizedString(@"Punk Rock", @"Musical genre"),
			NSLocalizedString(@"Drum Solo", @"Musical genre"),
			NSLocalizedString(@"A cappella", @"Musical genre"),
			NSLocalizedString(@"Euro-House", @"Musical genre"),
			NSLocalizedString(@"Dance Hall", @"Musical genre"),
			NSLocalizedString(@"Goa", @"Musical genre"),
			NSLocalizedString(@"Drum & Bass", @"Musical genre"),
			NSLocalizedString(@"Club-House", @"Musical genre"),
			NSLocalizedString(@"Hardcore", @"Musical genre"),
			NSLocalizedString(@"Terror", @"Musical genre"),
			NSLocalizedString(@"Indie", @"Musical genre"),
			NSLocalizedString(@"BritPop", @"Musical genre"),
			NSLocalizedString(@"Negerpunk", @"Musical genre"),
			NSLocalizedString(@"Polsk Punk", @"Musical genre"),
			NSLocalizedString(@"Beat", @"Musical genre"),
			NSLocalizedString(@"Christian gangsta rap", @"Musical genre"),
			NSLocalizedString(@"Heavy Metal", @"Musical genre"),
			NSLocalizedString(@"Black Metal", @"Musical genre"),
			NSLocalizedString(@"Crossover", @"Musical genre"),
			NSLocalizedString(@"Contemporary Christian", @"Musical genre"),
			NSLocalizedString(@"Christian Rock", @"Musical genre"),
			NSLocalizedString(@"Merengue", @"Musical genre"),
			NSLocalizedString(@"Salsa", @"Musical genre"),
			NSLocalizedString(@"Thrash Metal", @"Musical genre"),
			NSLocalizedString(@"Anime", @"Musical genre"),
			NSLocalizedString(@"JPop", @"Musical genre"),
			NSLocalizedString(@"Synthpop", @"Musical genre"),
			nil];
}

// ========================================
// Returns an alphabetically sorted array containing the ID3v1 genres and WinAmp extensions
// ========================================
NSArray * sortedGenres()
{
	return [genres() sortedArrayUsingSelector:@selector(compare:)];
}
