/*
 *  Copyright (C) 2006 - 2008 Stephen F. Booth <me@sbooth.org>
 *  All Rights Reserved
 */

#import "GenreUtilities.h"

// ========================================
// Returns an array containing the ID3v1 genres and WinAmp extensions
// ========================================
NSArray * genres()
{
	return [[NSArray alloc] initWithObjects:
			// ID3v1 genres
			NSLocalizedStringFromTable(@"Blues", @"Genres", @""),
			NSLocalizedStringFromTable(@"Classic Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Country", @"Genres", @""),
			NSLocalizedStringFromTable(@"Dance", @"Genres", @""),
			NSLocalizedStringFromTable(@"Disco", @"Genres", @""),
			NSLocalizedStringFromTable(@"Funk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Grunge", @"Genres", @""),
			NSLocalizedStringFromTable(@"Hip-Hop", @"Genres", @""),
			NSLocalizedStringFromTable(@"Jazz", @"Genres", @""),
			NSLocalizedStringFromTable(@"Metal", @"Genres", @""),
			NSLocalizedStringFromTable(@"New Age", @"Genres", @""),
			NSLocalizedStringFromTable(@"Oldies", @"Genres", @""),
			NSLocalizedStringFromTable(@"Other", @"Genres", @""),
			NSLocalizedStringFromTable(@"Pop", @"Genres", @""),
			NSLocalizedStringFromTable(@"R&B", @"Genres", @""),
			NSLocalizedStringFromTable(@"Rap", @"Genres", @""),
			NSLocalizedStringFromTable(@"Reggae", @"Genres", @""),
			NSLocalizedStringFromTable(@"Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Techno", @"Genres", @""),
			NSLocalizedStringFromTable(@"Industrial", @"Genres", @""),
			NSLocalizedStringFromTable(@"Alternative", @"Genres", @""),
			NSLocalizedStringFromTable(@"Ska", @"Genres", @""),
			NSLocalizedStringFromTable(@"Death metal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Pranks", @"Genres", @""),
			NSLocalizedStringFromTable(@"Soundtrack", @"Genres", @""),
			NSLocalizedStringFromTable(@"Euro-Techno", @"Genres", @""),
			NSLocalizedStringFromTable(@"Ambient", @"Genres", @""),
			NSLocalizedStringFromTable(@"Trip-hop", @"Genres", @""),
			NSLocalizedStringFromTable(@"Vocal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Jazz+Funk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Fusion", @"Genres", @""),
			NSLocalizedStringFromTable(@"Trance", @"Genres", @""),
			NSLocalizedStringFromTable(@"Classical", @"Genres", @""),
			NSLocalizedStringFromTable(@"Instrumental", @"Genres", @""),
			NSLocalizedStringFromTable(@"Acid", @"Genres", @""),
			NSLocalizedStringFromTable(@"House", @"Genres", @""),
			NSLocalizedStringFromTable(@"Game", @"Genres", @""),
			NSLocalizedStringFromTable(@"Sound Clip", @"Genres", @""),
			NSLocalizedStringFromTable(@"Gospel", @"Genres", @""),
			NSLocalizedStringFromTable(@"Noise", @"Genres", @""),
			NSLocalizedStringFromTable(@"Alt. Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Bass", @"Genres", @""),
			NSLocalizedStringFromTable(@"Soul", @"Genres", @""),
			NSLocalizedStringFromTable(@"Punk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Space", @"Genres", @""),
			NSLocalizedStringFromTable(@"Meditative", @"Genres", @""),
			NSLocalizedStringFromTable(@"Instrumental pop", @"Genres", @""),
			NSLocalizedStringFromTable(@"Instrumental rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Ethnic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Gothic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Darkwave", @"Genres", @""),
			NSLocalizedStringFromTable(@"Techno-Industrial", @"Genres", @""),
			NSLocalizedStringFromTable(@"Electronic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Pop-Folk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Eurodance", @"Genres", @""),
			NSLocalizedStringFromTable(@"Dream", @"Genres", @""),
			NSLocalizedStringFromTable(@"Southern Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Comedy", @"Genres", @""),
			NSLocalizedStringFromTable(@"Cult", @"Genres", @""),
			NSLocalizedStringFromTable(@"Gangsta", @"Genres", @""),
			NSLocalizedStringFromTable(@"Top 40", @"Genres", @""),
			NSLocalizedStringFromTable(@"Christian Rap", @"Genres", @""),
			NSLocalizedStringFromTable(@"Pop/Funk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Jungle", @"Genres", @""),
			NSLocalizedStringFromTable(@"Native American", @"Genres", @""),
			NSLocalizedStringFromTable(@"Cabaret", @"Genres", @""),
			NSLocalizedStringFromTable(@"New Wave", @"Genres", @""),
			NSLocalizedStringFromTable(@"Psychedelic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Rave", @"Genres", @""),
			NSLocalizedStringFromTable(@"Showtunes", @"Genres", @""),
			NSLocalizedStringFromTable(@"Trailer", @"Genres", @""),
			NSLocalizedStringFromTable(@"Lo-Fi", @"Genres", @""),
			NSLocalizedStringFromTable(@"Tribal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Acid Punk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Acid Jazz", @"Genres", @""),
			NSLocalizedStringFromTable(@"Polka", @"Genres", @""),
			NSLocalizedStringFromTable(@"Retro", @"Genres", @""),
			NSLocalizedStringFromTable(@"Musical", @"Genres", @""),
			NSLocalizedStringFromTable(@"Rock & Roll", @"Genres", @""),
			NSLocalizedStringFromTable(@"Hard Rock", @"Genres", @""),

			// WinAmp extensions
			NSLocalizedStringFromTable(@"Folk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Folk-Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"National Folk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Swing", @"Genres", @""),
			NSLocalizedStringFromTable(@"Fast Fusion", @"Genres", @""),
			NSLocalizedStringFromTable(@"Bebob", @"Genres", @""),
			NSLocalizedStringFromTable(@"Latin", @"Genres", @""),
			NSLocalizedStringFromTable(@"Revival", @"Genres", @""),
			NSLocalizedStringFromTable(@"Celtic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Bluegrass", @"Genres", @""),
			NSLocalizedStringFromTable(@"Avantgarde", @"Genres", @""),
			NSLocalizedStringFromTable(@"Gothic Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Progressive Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Psychedelic Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Symphonic Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Slow Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Big Band", @"Genres", @""),
			NSLocalizedStringFromTable(@"Chorus", @"Genres", @""),
			NSLocalizedStringFromTable(@"Easy Listening", @"Genres", @""),
			NSLocalizedStringFromTable(@"Acoustic", @"Genres", @""),
			NSLocalizedStringFromTable(@"Humour", @"Genres", @""),
			NSLocalizedStringFromTable(@"Speech", @"Genres", @""),
			NSLocalizedStringFromTable(@"Chanson", @"Genres", @""),
			NSLocalizedStringFromTable(@"Opera", @"Genres", @""),
			NSLocalizedStringFromTable(@"Chamber Music", @"Genres", @""),
			NSLocalizedStringFromTable(@"Sonata", @"Genres", @""),
			NSLocalizedStringFromTable(@"Symphony", @"Genres", @""),
			NSLocalizedStringFromTable(@"Booty Bass", @"Genres", @""),
			NSLocalizedStringFromTable(@"Primus", @"Genres", @""),
			NSLocalizedStringFromTable(@"Porn Groove", @"Genres", @""),
			NSLocalizedStringFromTable(@"Satire", @"Genres", @""),
			NSLocalizedStringFromTable(@"Slow Jam", @"Genres", @""),
			NSLocalizedStringFromTable(@"Club", @"Genres", @""),
			NSLocalizedStringFromTable(@"Tango", @"Genres", @""),
			NSLocalizedStringFromTable(@"Samba", @"Genres", @""),
			NSLocalizedStringFromTable(@"Folklore", @"Genres", @""),
			NSLocalizedStringFromTable(@"Ballad", @"Genres", @""),
			NSLocalizedStringFromTable(@"Power Ballad", @"Genres", @""),
			NSLocalizedStringFromTable(@"Rhythmic Soul", @"Genres", @""),
			NSLocalizedStringFromTable(@"Freestyle", @"Genres", @""),
			NSLocalizedStringFromTable(@"Duet", @"Genres", @""),
			NSLocalizedStringFromTable(@"Punk Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Drum Solo", @"Genres", @""),
			NSLocalizedStringFromTable(@"A cappella", @"Genres", @""),
			NSLocalizedStringFromTable(@"Euro-House", @"Genres", @""),
			NSLocalizedStringFromTable(@"Dance Hall", @"Genres", @""),
			NSLocalizedStringFromTable(@"Goa", @"Genres", @""),
			NSLocalizedStringFromTable(@"Drum & Bass", @"Genres", @""),
			NSLocalizedStringFromTable(@"Club-House", @"Genres", @""),
			NSLocalizedStringFromTable(@"Hardcore", @"Genres", @""),
			NSLocalizedStringFromTable(@"Terror", @"Genres", @""),
			NSLocalizedStringFromTable(@"Indie", @"Genres", @""),
			NSLocalizedStringFromTable(@"BritPop", @"Genres", @""),
			NSLocalizedStringFromTable(@"Negerpunk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Polsk Punk", @"Genres", @""),
			NSLocalizedStringFromTable(@"Beat", @"Genres", @""),
			NSLocalizedStringFromTable(@"Christian gangsta rap", @"Genres", @""),
			NSLocalizedStringFromTable(@"Heavy Metal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Black Metal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Crossover", @"Genres", @""),
			NSLocalizedStringFromTable(@"Contemporary Christian", @"Genres", @""),
			NSLocalizedStringFromTable(@"Christian Rock", @"Genres", @""),
			NSLocalizedStringFromTable(@"Merengue", @"Genres", @""),
			NSLocalizedStringFromTable(@"Salsa", @"Genres", @""),
			NSLocalizedStringFromTable(@"Thrash Metal", @"Genres", @""),
			NSLocalizedStringFromTable(@"Anime", @"Genres", @""),
			NSLocalizedStringFromTable(@"JPop", @"Genres", @""),
			NSLocalizedStringFromTable(@"Synthpop", @"Genres", @""),
			nil];
}

// ========================================
// Returns an alphabetically sorted array containing the ID3v1 genres and WinAmp extensions
// ========================================
NSArray * sortedGenres()
{
	return [genres() sortedArrayUsingSelector:@selector(compare:)];
}
